function [model_path, model_name] = build_turtlebot_simulink_model(cfg, out_dir)
%BUILD_TURTLEBOT_SIMULINK_MODEL Programmatically build the SGF TurtleBot swarm model.
%
%   Constructs models/sgf_turtlebot_swarm.slx as a genuine Simulink block diagram:
%
%       [ Integrator (3n states) ] --> [ MATLAB Function: swarm_ode ] --,
%              ^------------------------------------------------------- '
%       Integrator output also branches to a To Workspace block (xout);
%       a Clock feeds a second To Workspace block (tout).
%
%   The MATLAB Function block "swarm_ode" implements the paper Eq. 4 sign
%   gradient-free controller on the control points s_i = p_i + r[cos th; sin th],
%   the saturated quadratic source measurement, unicycle feedback linearization,
%   and the differential-drive kinematic derivative -- identical math to the
%   Phase 1.3 helpers sgf_control / sgf_measurement, baked in as numeric literals
%   so the .slx is self-contained and codegen-safe for the chosen config.
%
%   The model is continuous (command_period = 0). A fixed-step solver (default
%   ode4) integrates the 3n-state vector [x_1..x_n, y_1..y_n, th_1..th_n].
%
%   Returns the saved model path and the model name.

if nargin < 2
    out_dir = fullfile(cfg.run_dir, 'models');
end
if ~exist(out_dir, 'dir')
    mkdir(out_dir);
end

if cfg.noise_model ~= "none"
    warning(['Simulink model is a deterministic continuous reference: forcing ' ...
        'noise=none (config requested "%s"). Compare against a noise=none numeric run.'], ...
        cfg.noise_model);
end

model_name = char(cfg.simulink_model_name);
solver = char(cfg.simulink_solver);

if bdIsLoaded(model_name)
    close_system(model_name, 0);
end

x0 = [cfg.initial_positions(:, 1); cfg.initial_positions(:, 2); cfg.initial_headings];
code = generate_ode_code(cfg);

new_system(model_name);
load_system(model_name);

% --- vector Integrator holding the 3n-dim state ------------------------------
add_block('simulink/Continuous/Integrator', [model_name '/state']);
set_param([model_name '/state'], 'InitialCondition', mat2str(x0(:)), ...
    'Position', [300, 100, 340, 140]);

% --- MATLAB Function block: state derivative ---------------------------------
add_block('simulink/User-Defined Functions/MATLAB Function', [model_name '/swarm_ode'], ...
    'Position', [120, 95, 240, 145]);
set_matlab_function_code(model_name, 'swarm_ode', code);

% --- logging -----------------------------------------------------------------
add_block('simulink/Sinks/To Workspace', [model_name '/xout'], ...
    'VariableName', 'xout', 'SaveFormat', 'Array', 'SampleTime', '-1', ...
    'Position', [430, 100, 490, 140]);
add_block('simulink/Sources/Clock', [model_name '/clock'], ...
    'Position', [430, 200, 460, 230]);
add_block('simulink/Sinks/To Workspace', [model_name '/tout'], ...
    'VariableName', 'tout', 'SaveFormat', 'Array', 'SampleTime', '-1', ...
    'Position', [510, 195, 570, 235]);

% --- wiring (feedback loop + branches to logging) ----------------------------
add_line(model_name, 'swarm_ode/1', 'state/1', 'autorouting', 'on');
add_line(model_name, 'state/1', 'swarm_ode/1', 'autorouting', 'on');
add_line(model_name, 'state/1', 'xout/1', 'autorouting', 'on');
add_line(model_name, 'clock/1', 'tout/1', 'autorouting', 'on');

% --- solver configuration ----------------------------------------------------
set_param(model_name, 'SolverType', 'Fixed-step', 'Solver', solver, ...
    'FixedStep', num2str(cfg.dt, '%.10g'), 'StopTime', num2str(cfg.duration, '%.10g'), ...
    'SaveOutput', 'off', 'SaveTime', 'off');

model_path = fullfile(out_dir, [model_name '.slx']);
save_system(model_name, model_path);
end


function set_matlab_function_code(model_name, block_name, code)
%SET_MATLAB_FUNCTION_CODE Set the script of a MATLAB Function (Stateflow EM chart).
root = sfroot;
chart = root.find('-isa', 'Stateflow.EMChart', 'Path', [model_name '/' block_name]);
if isempty(chart)
    error('Could not locate MATLAB Function block %s/%s.', model_name, block_name);
end
chart.Script = code;
end


function code = generate_ode_code(cfg)
%GENERATE_ODE_CODE Emit the swarm_ode MATLAB Function body with baked literals.
n = cfg.n;
theta = 2 * pi * (0:(n - 1))' / n;
phi = [cos(theta), sin(theta)];

adj_lit = mat2str(double(cfg.adjacency ~= 0));
phi_lit = mat2str(phi, 15);
src_lit = mat2str(cfg.source(:)', 15);

lines = {
    'function dx = swarm_ode(x)'
    '%#codegen'
    '% Auto-generated by build_turtlebot_simulink_model. Do not edit by hand.'
    sprintf('n = %d;', n)
    sprintf('r = %.15g;', cfg.offset)
    sprintf('R = %.15g;', cfg.R)
    sprintf('kappa = %.15g;', cfg.kappa)
    sprintf('Dmax = %.15g;', cfg.Dmax)
    sprintf('alpha = %.15g;', cfg.alpha)
    sprintf('beta = %.15g;', cfg.beta)
    sprintf('noise_bound = %.15g;', cfg.noise_bound)
    sprintf('eps_bl = %.15g;', cfg.sign_boundary_layer)
    sprintf('src = %s;', src_lit)
    sprintf('adj = %s;', adj_lit)
    sprintf('phi = %s;', phi_lit)
    'px = x(1:n);'
    'py = x(n+1:2*n);'
    'th = x(2*n+1:3*n);'
    'sx = px + r .* cos(th);'
    'sy = py + r .* sin(th);'
    'zx = sx - R .* phi(:,1);'
    'zy = sy - R .* phi(:,2);'
    'dx = zeros(3*n, 1);'
    'for i = 1:n'
    '    fx = 0.0;'
    '    fy = 0.0;'
    '    for j = 1:n'
    '        if adj(i,j) ~= 0'
    '            fx = fx + alpha * ssign(zx(j) - zx(i), eps_bl);'
    '            fy = fy + alpha * ssign(zy(j) - zy(i), eps_bl);'
    '        end'
    '    end'
    '    dsx = sx(i) - src(1);'
    '    dsy = sy(i) - src(2);'
    '    dist = sqrt(dsx*dsx + dsy*dsy);'
    '    if dist < Dmax'
    '        sigma = kappa * (dsx*dsx + dsy*dsy);'
    '    else'
    '        sigma = kappa * Dmax * Dmax + noise_bound;'
    '    end'
    '    fx = fx - (2*beta/R) * sigma * phi(i,1);'
    '    fy = fy - (2*beta/R) * sigma * phi(i,2);'
    '    c = cos(th(i));'
    '    s = sin(th(i));'
    '    v = c*fx + s*fy;'
    '    om = (-s*fx + c*fy) / r;'
    '    dx(i)       = v * c;'
    '    dx(n+i)     = v * s;'
    '    dx(2*n+i)   = om;'
    'end'
    'end'
    ''
    'function y = ssign(d, eps)'
    '% Component-wise signum, or boundary-layer saturation sat(d/eps) when eps > 0.'
    'if eps > 0'
    '    y = max(min(d / eps, 1.0), -1.0);'
    'else'
    '    y = sign(d);'
    'end'
    'end'
    };

code = strjoin(lines, newline);
end
